additional:
  - "action-terraform-report"

files:
  - "!.github/workflows/push.yml"
  - "!.gitignore"
  - "!**/template-sync.yml"
  - "!action.yml"
  - "!colophon.yml"
  - "!docker-compose.yml"
  - "!docs/**"
  - "!Makefile"
  - "!README.md"
