additional:
  - "action-terraform-report"
  - "action-template-repository-sync"

files:
  - "!.github/test-matrix.json"
  - "!**.js"
  - "!**/template-sync.yml"
  - "!action.yml"
  - "!colophon.yml"
  - "!docs/README.md"
  - "!package*.json"
  - "!README.md"
  - "!.github/dependabot.yml"
  - .github/dependabot-template.yml: .github/dependabot.yml
