additional:
  - "action-terraform-report"

files:
  - "!.github/test-matrix.json"
  - "!**.js"
  - "!**/template-sync.yml"
  - "!action.yml"
  - "!colophon.yml"
  - "!docs/README.md"
  - "!package*.json"
  - "!README.md"
