name: GitHub Action Template
description: A template for GitHub Actions

branding:
  color: purple
  icon: monitor

inputs:
  github-token:
    description: The GitHub token used to post comments on pull requests
    default: ${{ github.token }}
    required: false

runs:
  using: node16
  main: dist/index.js
