# -------------------------------------------------- #
# Note: this file originates in template-action-node #
# -------------------------------------------------- #

services:
  # ---- super-linter ---- #
  lint:
    profiles: ["dev"]
    image: github/super-linter:slim-v4
    volumes:
      - ./:/github/workspace
    environment:
      RUN_LOCAL: 'true'
      LOG_LEVEL: 'ERROR'
      MULTI_STATUS: 'false'
      IGNORE_GITIGNORED_FILES: 'true'
      DEFAULT_WORKSPACE: /github/workspace
      FILTER_REGEX_EXCLUDE: '/github/workspace/README.md|test/fixtures/*|dist/**'

  # ---- readme generator ---- #
  readme:
    profiles: ["dev"]
    image: pandoc/core:2.13
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml

  app: &app
    profiles: ["app"]
    image: node:alpine
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: npm --no-update-notifier run test -- --reporter=classic

  test:
    <<: *app
    profiles: ["test"]
    image: node:alpine
